services:
  client:
    container_name: prtl-base-client
    build:
      context: .
    ports:
      - "5173:5173"
    environment:
      - ENV=local
    volumes:
      - ./:/app
      - /app/node_modules
